### ISSUE TITLE
Allow chart customisation range and interval

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM_UI#22]
**Describe the bug**

adjust for both charts

**Steps to recreate the bug**

Versions: Revit , Rhino

**Screenshots**

![image](https://user-images.githubusercontent.com/26113670/177521062-a06dee5b-c526-4708-bb1d-1dd68ea0be49.png)

**Test file**

**Comment by MaciejDengusiak** [comment]
Solved #41
