### ISSUE TITLE
rounding

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM_UI#39]
**Describe the bug**

rounding to 2 desimal

**Steps to recreate the bug**

Versions: Revit , Rhino

**Screenshots**

![image](https://user-images.githubusercontent.com/26113670/179261858-d0fba2c3-ed3e-49db-bae7-fd6a0557b141.png)

**Test file**

**Comment by MaciejDengusiak** [comment]
Solved #41
